#@ load("@ytt:data", "data")
---
spring:
  cloud:
    gateway:
      routes:
        - id: frontend-service-route
          uri:  lb://frontend
          predicates:
            - Path=/frontend/**
          filters:
            - StripPrefix=1
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/services/product-service/**
          filters:
            - StripPrefix=2
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/services/order-service/**
          filters:
            - StripPrefix=2
