apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  description: Spring Cloud Architecture on TAP Order Service
  tags:
    - sc-architecture
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=order-service'
    'backstage.io/techdocs-ref': dir:../../
spec:
  type: service
  lifecycle: experimental
  owner: team-vmware-tanzu-se
  system: sc-architecture-system
  dependsOn:
  - Resource:authserver-1
  - Resource:configserver
  - Resource:observability
  - Resource:rmq-1
  - Resource:postgres-1
  - Resource:gemfire-1
  - Component:product-service
  - Component:shipping-service