apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: frontend
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: frontend
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
spec:
  source:
    git:
      url: https://github.com/tsalm-pivotal/spring-cloud-demo-tap.git
      ref:
        branch: main
    subPath: frontend
  build:
    env:
    - name: BP_NODE_RUN_SCRIPTS
      value: build
    - name: BP_WEB_SERVER
      value: nginx
    - name: BP_WEB_SERVER_ROOT
      value: dist/frontend
    - name: BP_WEB_SERVER_ENABLE_PUSH_STATE
      value: "true"